version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:4.0-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./config/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq_network

  rabbitmq2:
    image: rabbitmq:4.0-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./config/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq_network

  rabbitmq3:
    image: rabbitmq:4.0-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    restart: unless-stopped
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./config/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq_network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "5670:5670"
      - "15670:15670"
      - "1936:1936"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge